apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
  name: {{ include "boundary.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["batch","apps"]
  resources: ["jobs","deployments"]
  verbs: ["list", "get"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
  name: {{ include "boundary.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "boundary.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "boundary.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
