apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convoy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "convoy.name" . }}
    helm.sh/chart: {{ include "convoy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "convoy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        updatedAt: {{ now | quote }}
      labels:
        app.kubernetes.io/name: {{ include "convoy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: convoy-config
          configMap:
            name: {{ include "convoy.fullname" . }}
            items: 
              - key: convoy.json
                path: convoy.json
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: convoy-config
              mountPath: /config
          command: ["/cmd"]
          args: ["server", "--config", "/config/convoy.json"]
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
            {{- range $env := .Values.app.env }}
            - name: {{ $env | upper }}
              valueFrom:
                secretKeyRef:
                  name: convoy
                  key: {{ $env }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- if .Values.podLabels }}
      {{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
