apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" .}}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  nginx.conf: |
    {{- tpl .Values.nginx.config.file . | nindent 4 }}
