apiVersion: v1
kind: Service
metadata:
  name: {{ template "gateway.service.name" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: http
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
