apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.broker.svc }}
spec:
  type: {{ .Values.cluster.broker.type }}
  selector:
    component: {{ .Values.cluster.broker.svc }}
  ports:
    -
      port: {{ .Values.cluster.broker.externalPort }}
      targetPort: {{ .Values.cluster.broker.internalPort }}