apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.broker.svc }}
  labels:
{{- if .Values.cluster.broker.podLabels }}
{{ toYaml .Values.cluster.broker.podLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.cluster.broker.type }}
  selector:
    component: {{ .Values.cluster.broker.svc }}
  ports:
    -
      port: {{ .Values.cluster.broker.externalPort }}
      targetPort: {{ .Values.cluster.broker.internalPort }}
