apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
  {{- with .Values.configMapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  Caddyfile: |
    {
      http_port {{ .Values.listenPort }}
    {{- if .Values.config.debug }}
      debug
    {{- end }}
      {{ .Values.config.global | nindent 6 }}
    }

    :9999 {
      handle {{ .Values.health.path }} {
        respond "OK"
      }
    }

    {{ .Values.config.caddyFile | nindent 4 }}
