apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
  {{- with .Values.configMapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  Caddyfile: |
    {
      http_port {{ .Values.listenPort }}
    {{- if .Values.config.debug }}
      debug
    {{- end }}
    {{- if .Values.config.metrics.enabled }}
      servers {
    	metrics
      }
      admin :{{ .Values.adminPort }}
    {{- end }}
      servers :{{ .Values.listenPort }} {
        name {{ include "caddy.name" . }}
      }
      {{ .Values.config.global | nindent 6 }}
    }

    :9999 {
      handle {{ .Values.health.path }} {
        respond "OK"
      }
    }
    {{ tpl .Values.config.services . | nindent 4 }}

    {{ tpl .Values.config.caddyFile . | nindent 4 }}
