apiVersion: v1
kind: Service
metadata:
{{- if .Values.adminService.name }}
  name: {{ .Values.adminService.name }}
{{- else }}
  name: {{ template "fullname" . }}-admin
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    app.kubernetes.io/name: {{ .Values.adminService.name }}
  annotations:
    livspace.com/service: {{ .Values.adminService.name }}
{{- if .Values.adminService.annotations }}
{{ toYaml .Values.adminService.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.adminService.type }}
  ports:
  - port: {{ .Values.adminService.externalPort }}
    targetPort: {{ .Values.adminService.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
