# Default values for convoy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  port: 3000
  env: []
#    - ssl
#    - worker_port
#    - convoy_env
#    - convoy_base_url
#    - convoy_db_type
#    - convoy_db_dsn
#    - convoy_sentry_dsn
#    - convoy_mutiple_tenants
#    - convoy_limiter_provider
#    - convoy_cache_provider
#    - convoy_queue_provider
#    - convoy_redis_dsn
#    - convoy_logger_level
#    - convoy_logger_provider
#    - convoy_ssl_key_file
#    - convoy_ssl_cert_file
#    - convoy_strategy_type
#    - convoy_signature_hash
#    - convoy_disable_endpoint
#    - convoy_signature_header
#    - convoy_interval_seconds
#    - convoy_smtp_url
#    - convoy_smtp_from
#    - convoy_smtp_port
#    - convoy_retry_limit
#    - convoy_require_auth
#    - convoy_smtp_provider
#    - convoy_smtp_username
#    - convoy_smtp_password
#    - convoy_smtp_reply_to
#    - convoy_api_key_config
#    - convoy_newrelic_app_name
#    - convoy_basic_auth_config
#    - convoy_newrelic_license_key
#    - convoy_native_realm_enabled
#    - convoy_newrelic_config_enabled
#    - convoy_newrelic_distributed_tracer_enabled
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

image:
  repository: ghcr.io/frain-dev/convoy
  pullPolicy: IfNotPresent
  tag: stable

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

config:
  enabled: false
#  convoy: {"environment":"dev","database":{"type":"mongodb","dsn":"mongodb://mongo1:27017,mongo2:27017,mongo3:27017/convoy?replicaSet=myReplicaSet&readPreference=primary&ssl=false"},"queue":{"type":"redis","redis":{"dsn":"redis://redis_server:6379"}},"cache":{"type":"redis","redis":{"dsn":"redis://redis_server:6379"}},"host":"{host}","logger":{"type":"console","server_log":{"level":"error"}},"smtp":{"provider":"sendgrid","url":"smtp.sendgrid.net","port":2525,"username":"apikey","password":"<api-key-from-sendgrid>","from":"support@frain.dev"},"search":{"type":"typesense","typesense":{"host":"http://typesense:8108","api_key":"convoy"}},"server":{"http":{"ssl":false,"ssl_cert_file":"","ssl_key_file":"","port":5005}},"auth":{"jwt":{"enabled":true},"native":{"enabled":true}}}
