apiVersion: v2
name: oneuptime
description: The Complete Open-Source Observability Platform
type: application
version: 0.1.1
appVersion: "1.16.0"
dependencies:
- name: postgresql
  version: "14.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: redis
  version: "18.19.1"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
- name: clickhouse
  version: "5.1.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: clickhouse.enabled

