apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.state.svc }}
  labels:
{{- if .Values.cluster.state.podLabels }}
{{ toYaml .Values.cluster.state.podLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.cluster.state.type }}
  selector:
    component: {{ .Values.cluster.state.svc }}
  ports:
    -
      port: {{ .Values.cluster.state.externalPort }}
      targetPort: {{ .Values.cluster.state.internalPort }}