# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
cluster:
  enabled: true
  state:
    svc: scc-state
    externalPort: 7777
    internalPort: 7777
    type: ClusterIP
#    podLabels:
#      lab: state
#    podAnnotations:
#      ann: state
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
#    volumeMounts:
#    - mountPath: /tmp
#      name: tmp-dir-volume
#    volumes:
#    - name: tmp-dir-volume
#      emptyDir: {}
    networkPolicy:
      enabled: false
      egress: []
        # toApps:
        #   - name: AppName
        #     namespace: TargetNamespace
        #     httpPorts: [8080]
        #     tcpPorts: [8081]
        #     udpPorts: []
  broker:
    type: ClusterIP
    svc: scc-broker
    replicaCount: '5'
    externalPort: 8888
    internalPort: 8888
#    podLabels:
#      lab: broker
#    podAnnotations:
#      ann: broker
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
#    volumeMounts:
#    - mountPath: /tmp
#      name: tmp-dir-volume
#    volumes:
#    - name: tmp-dir-volume
#      emptyDir: {}
    networkPolicy:
      enabled: false
      egress: []
        # toApps:
        #   - name: AppName
        #     namespace: TargetNamespace
        #     httpPorts: [8080]
        #     tcpPorts: [8081]
        #     udpPorts: []
  scService:
    image:
      repository: draft
      tag: dev
      pullPolicy: IfNotPresent
#    podLabels:
#      lab: worker
#    podAnnotations:
#      ann: worker
    replicaCount: '5'
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
#    volumeMounts:
#    - mountPath: /tmp
#      name: tmp-dir-volume
#    volumes:
#    - name: tmp-dir-volume
#      emptyDir: {}
    networkPolicy:
      enabled: false
      egress: []
        # toApps:
        #   - name: AppName
        #     namespace: TargetNamespace
        #     httpPorts: [8080]
        #     tcpPorts: [8081]
        #     udpPorts: []
service:
  name: chat
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  wsExternalPort: 8000
  wsInternalPort: 8000
  annotations: {}
  gateway:
    enabled: true
    routes:
      api: {}
      ws:
        prefix: /chat/socketcluster/
        extra:
          precedence: 2
          rewrite: /socketcluster/
          use_websocket: true
          bypass_auth: true

probePath: /health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

ingress:
  enabled: false

env:
  enabled: true
  values:
  - name: NODE_ENV
    value: local
  - name: APP_CONFIG_DIR
    value: /etc/liv-chat
  - name: SCC_STATE_SERVER_HOST
    value: scc-state
  - name: SOCKETCLUSTER_WORKERS
    value: '1'
  - name: SOCKETCLUSTER_BROKERS
    value: '1'

config:
  enabled: false
  mountPath: /etc/liv-chat
  files:
    config.yml: |-
      profiling:                      No
