apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name | default (include "rudderstack.fullname" .) }}
  labels:
    {{- include "rudderstack.labels" . | nindent 4 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 4 }}
{{- end }}
  annotations:
  {{- with .Values.backend.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
  {{- with .Values.backend.service.selectorLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
#     {{- include "rudderstack.selectorLabels" . | nindent 4 }}
