{{- if $.Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "application.name" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "application.name" . }}
  policyTypes:
  {{- if .Values.networkPolicy.ingress }}
  - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  - Egress
  {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
  {{- range $rule := .Values.networkPolicy.ingress.fromApps }}
  {{- if or $rule.httpPorts $rule.tcpPorts $rule.udpPorts }}
  {{- $labelKey := default "app" $rule.labelKey }}
  - from:
    - podSelector:
        matchLabels:
          {{ $labelKey }}: {{ $rule.name }}
      {{- if $rule.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $rule.namespace }}
      {{- end }}
    ports:
    {{- range $port := $rule.httpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $rule.tcpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $rule.udpPorts }}
    - port: {{ $port }}
      protocol: UDP
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
  {{- range $app := .Values.networkPolicy.egress.toApps }}
  {{- if or $app.httpPorts $app.tcpPorts $app.udpPorts }}
  {{- $labelKey := default "app" $app.labelKey }}
  - to:
    - podSelector:
        matchLabels:
          {{ $labelKey }}: {{ $app.name }}
      {{- if $app.namespace }}
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $app.namespace }}
      {{- end }}
    ports:
    {{- range $port := $app.httpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.tcpPorts }}
    - port: {{ $port }}
      protocol: TCP
    {{- end }}
    {{- range $port := $app.udpPorts }}
    - port: {{ $port }}
      protocol: UDP
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}