{{- if $.Values.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "application.name" . }}-egress
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "application.name" . }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ template "application.name" . }}
  egress:
  {{- range $egress := .Values.networkPolicy.egress }}
  - toEndpoints:
      - matchLabels:
          app: {{ $egress.host }}
    toPorts:
      - ports: 
        - port: "{{ $egress.port }}"
          protocol: TCP
        {{- if eq $egress.protocol "http" }}
        rules:
          http: [{}]
        {{- end }}
  {{- end }}
  - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s:k8s-app: kube-dns
    toPorts:
      - ports:
        - port: "53"
          protocol: ANY
        rules:
          dns:
          - matchPattern: '*'
{{- end }}