{{- if $.Values.serviceAccount }}
{{- if $.Values.serviceAccount.create }}
{{- $cloudProvider := .Values.cloud.provider }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ default false $.Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "serviceAccountName" . }}
  {{- if .Values.podLabels }}
  labels:
{{ toYaml .Values.podLabels | indent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.serviceAccount.annotations }}
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
  {{- if and (not (hasKey .Values.serviceAccount.annotations "iam.gke.io/gcp-service-account")) (eq $cloudProvider "gcp") }}
    {{- $gcpSuffix := "livspace-staging-apps.iam.gserviceaccount.com" }}
    iam.gke.io/gcp-service-account: {{ printf "%s@%s" (include "serviceAccountName" .) $gcpSuffix }}
  {{- end }}
{{- end -}}
{{- end -}}
