name: Release Charts

on:
  push:
    branches:
      - master
      - next
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
#        with:
#          version: v4.1.0

#      - name: Set up Helm repos
#        run: |
#          helm repo add bitnami https://charts.bitnami.com/bitnami/
#          helm repo add elastic https://helm.elastic.co
      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_repo_url: https://charts.livspace.com
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
